fullname = input("Enter your fullname:")
print(fullname)
address = input("Enter your address:")
print(address)
birthday = input("Enter your birthday:")
print(birthday)

college = input("Name of your college:")
print(college)
course = input("Course:")
print(course)
year = input("Year:")
print(year)
section = input("Section:")
print(section)